# Generated by Django 4.1 on 2023-05-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Typ"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Name"
                    ),
                ),
                ("email", models.EmailField(max_length=300, verbose_name="Email")),
                (
                    "telnr",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Telefon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.contact",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Stadt"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=2000, null=True, verbose_name="Website"
                    ),
                ),
            ],
            bases=("main.contact",),
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Newsletter Name"),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        blank=True, related_name="newsletter", to="main.contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.contact",
                    ),
                ),
                (
                    "group",
                    models.ManyToManyField(
                        blank=True, related_name="member", to="main.group"
                    ),
                ),
            ],
            bases=("main.contact",),
        ),
        migrations.AddField(
            model_name="group",
            name="main_contact",
            field=models.ManyToManyField(
                blank=True, related_name="leading_group", to="main.person"
            ),
        ),
    ]
