# Generated by Django 4.1 on 2023-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notizen"),
        ),
    ]
